### ISSUE TITLE
Model Loading

### ISSUE THREAD

**Issue by zeroxthreef** [LukasBanana/PicoRenderer#2]
Is the .pico format a custom format, or is it similar to some other kind of format? The files seem to be loaded in as raw vertex and index buffer data, however I cant figure out the full structure.

**Comment by LukasBanana** [comment]
Take a look at the [`_pr_vertexbuffer_data_from_file`](https://github.com/LukasBanana/PicoRenderer/blob/master/src/rasterizer/vertexbuffer.c#L175) function. It's only a very primitive vertex data format.
