### ISSUE TITLE
reserved identifier violation

### ISSUE THREAD

**Issue by elfring** [LukasBanana/PicoRenderer#3]
I would like to point out that an identifier like “[`__PR_PICO_H__`](https://github.com/LukasBanana/PicoRenderer/blob/164278f4815644f7d77384b1472bc534faf76f86/inc/pico.h#L8 "Update candidate")” [does eventually not fit](https://www.securecoding.cert.org/confluence/display/c/DCL37-C.+Do+not+declare+or+define+a+reserved+identifier#DCL37-C.Donotdeclareordefineareservedidentifier-NoncompliantCodeExample%28IncludeGuard%29 "Do not use identifiers which are reserved for the compiler implementation.") to the expected naming convention of the C language standard.
Would you like to adjust your selection for unique names?

**Comment by LukasBanana** [comment]
Fixed with [27a4cb3](https://github.com/LukasBanana/PicoRenderer/commit/27a4cb39a0c5c71135693964654fe32b82affcd4).

**Comment by elfring** [comment]
Thanks for [your renaming of affected include guards](https://github.com/LukasBanana/PicoRenderer/commit/27a4cb39a0c5c71135693964654fe32b82affcd4 "Renaming of header guards").

[A few update candidates were left over](https://github.com/LukasBanana/PicoRenderer/blob/8234e81f62be3366f5fa38c3c17e86b3b49e5387/src/platform/linux/context.h#L8 "Another update candidate").

**Comment by LukasBanana** [comment]
Thanks for the hint. Fixed with [c633eae](https://github.com/LukasBanana/PicoRenderer/commit/c633eae16e2f9da627c7563353642bc5b3d0d9f6).

Just out of curiosity, since you once wrote the exact same message in my [LLGL project](https://github.com/LukasBanana/LLGL/issues/2): you are not a "Commit Bot" or something?

**Comment by elfring** [comment]
Thanks for [another small source code improvement](https://github.com/LukasBanana/PicoRenderer/commit/c633eae16e2f9da627c7563353642bc5b3d0d9f6 "Fixed remaining header guards for other platforms.").

This software implementation was affected for a while in similar ways which were already known from other components.
